// Generated by CoffeeScript 1.6.3
var filename, start;

start = require('./main').start;

filename = process.argv[2];

if (filename != null) {
  start(process.argv[2]);
} else {
  console.log('[Error]: no filename specified, exit');
}
