// Generated by CoffeeScript 1.6.3
var ast, parse, stringify;

parse = require('cirru-parser').parse;

stringify = function(object) {
  return JSON.stringify(object, null, 2);
};

ast = parse('../test/code.cr');

ast.error({
  text: 'demo',
  x: 1,
  y: 1
});
