// Generated by CoffeeScript 1.6.3
var __slice = [].slice;

exports.type = function(x) {
  return Object.prototype.toString.call(x).slice(1, -1).split(' ')[1].toLowerCase();
};

exports.stringify = function(object) {
  return JSON.stringify(object, null, 2);
};

exports.print = function() {
  var xs;
  xs = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  return console.log.apply(console, xs);
};

exports.write = function() {
  var xs, _ref;
  xs = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  return (_ref = require('util')).print.apply(_ref, xs);
};

exports.assert = function() {
  var xs;
  xs = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  return console.assert.apply(console, xs);
};

/*
//@ sourceMappingURL=tool.map
*/
